// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package appMock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type Logger
func (_mock *Logger) Error(ctx context.Context, err error, fields map[string]any) {
	_mock.Called(ctx, err, fields)
	return
}

// Logger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Logger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
//   - fields map[string]any
func (_e *Logger_Expecter) Error(ctx interface{}, err interface{}, fields interface{}) *Logger_Error_Call {
	return &Logger_Error_Call{Call: _e.mock.On("Error", ctx, err, fields)}
}

func (_c *Logger_Error_Call) Run(run func(ctx context.Context, err error, fields map[string]any)) *Logger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Logger_Error_Call) Return() *Logger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Error_Call) RunAndReturn(run func(ctx context.Context, err error, fields map[string]any)) *Logger_Error_Call {
	_c.Run(run)
	return _c
}

// Log provides a mock function for the type Logger
func (_mock *Logger) Log(ctx context.Context, message string, fields map[string]any) {
	_mock.Called(ctx, message, fields)
	return
}

// Logger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type Logger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - fields map[string]any
func (_e *Logger_Expecter) Log(ctx interface{}, message interface{}, fields interface{}) *Logger_Log_Call {
	return &Logger_Log_Call{Call: _e.mock.On("Log", ctx, message, fields)}
}

func (_c *Logger_Log_Call) Run(run func(ctx context.Context, message string, fields map[string]any)) *Logger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Logger_Log_Call) Return() *Logger_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Log_Call) RunAndReturn(run func(ctx context.Context, message string, fields map[string]any)) *Logger_Log_Call {
	_c.Run(run)
	return _c
}
