// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package appmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/t5mx27dp/app"
)

// NewRunnable creates a new instance of Runnable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runnable {
	mock := &Runnable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Runnable is an autogenerated mock type for the Runnable type
type Runnable struct {
	mock.Mock
}

type Runnable_Expecter struct {
	mock *mock.Mock
}

func (_m *Runnable) EXPECT() *Runnable_Expecter {
	return &Runnable_Expecter{mock: &_m.Mock}
}

// SetUp provides a mock function for the type Runnable
func (_mock *Runnable) SetUp(ctx context.Context, spawn app.Spawn) error {
	ret := _mock.Called(ctx, spawn)

	if len(ret) == 0 {
		panic("no return value specified for SetUp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.Spawn) error); ok {
		r0 = returnFunc(ctx, spawn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runnable_SetUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUp'
type Runnable_SetUp_Call struct {
	*mock.Call
}

// SetUp is a helper method to define mock.On call
//   - ctx context.Context
//   - spawn app.Spawn
func (_e *Runnable_Expecter) SetUp(ctx interface{}, spawn interface{}) *Runnable_SetUp_Call {
	return &Runnable_SetUp_Call{Call: _e.mock.On("SetUp", ctx, spawn)}
}

func (_c *Runnable_SetUp_Call) Run(run func(ctx context.Context, spawn app.Spawn)) *Runnable_SetUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.Spawn
		if args[1] != nil {
			arg1 = args[1].(app.Spawn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runnable_SetUp_Call) Return(err error) *Runnable_SetUp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runnable_SetUp_Call) RunAndReturn(run func(ctx context.Context, spawn app.Spawn) error) *Runnable_SetUp_Call {
	_c.Call.Return(run)
	return _c
}

// TearDown provides a mock function for the type Runnable
func (_mock *Runnable) TearDown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// Runnable_TearDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TearDown'
type Runnable_TearDown_Call struct {
	*mock.Call
}

// TearDown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runnable_Expecter) TearDown(ctx interface{}) *Runnable_TearDown_Call {
	return &Runnable_TearDown_Call{Call: _e.mock.On("TearDown", ctx)}
}

func (_c *Runnable_TearDown_Call) Run(run func(ctx context.Context)) *Runnable_TearDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runnable_TearDown_Call) Return() *Runnable_TearDown_Call {
	_c.Call.Return()
	return _c
}

func (_c *Runnable_TearDown_Call) RunAndReturn(run func(ctx context.Context)) *Runnable_TearDown_Call {
	_c.Run(run)
	return _c
}
